Widen integrations-api to check whether keychain is locked
cryptomator/integrations-linux pull request #10
Opened 2021-02-20 17:30 UTC by purejava

Fixes https://github.com/cryptomator/cryptomator/issues/1526

2021-02-22 10:48 UTC, infeo requested changes
Just a tiny change. If this is done, the PR is good to go.

2021-02-22 10:48 UTC, infeo commented on integrations-linux.iml
> +<module type="JAVA_MODULE" version="4" />
Please revert this change.

2021-02-22 10:52 UTC, infeo commented
I just noticed, that this PR also includes an updated kde-wallet dependency. For this change already PR #3 exists.

@purejava Contains kde wallet 1.2.0 any changes, that are necessary for the `isLocked()` mechanism?

2021-02-22 16:22 UTC, purejava commented on integrations-linux.iml
> +<module type="JAVA_MODULE" version="4" />
Yep

2021-02-22 16:28 UTC, purejava commented
> I just noticed, that this PR also includes an updated kde-wallet dependency. For this change already PR #3 exists.
> 
> @purejava Contains kde wallet 1.2.0 any changes, that are necessary for the `isLocked()` mechanism?

No, 1.2.0 does not have any changes that are needed for the `isLocked()` mechanism.
1.2.0 has an improved logging and new features. I thought it's alway best to go with the latest version but I can change that back to 1.1.1 of course.

2021-02-23 10:23 UTC, infeo approved these changes

2021-02-23 10:27 UTC, infeo commented
> I thought it's alway best to go with the latest version but I can change that back to 1.1.1 of course.
While generally i would also favor that, in this case the version bump contains bigger changes which needed to be looked at and tested (...again^^ the last time i looked at it is already a while ago)

2021-02-23 10:28 UTC, merged